apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-db-config
  annotations:
    kubernetes.io/description: Contains the configuration for the postgres DB
data:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "todos_db"
