apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  annotations:
    kubernetes.io/description: Contains the configuration for the Todo App
data:
  NODE_ENV : production
  PORT : "3000"
  DB_HOST : todo-db.default.svc.cluster.local
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT : "5432"
  DB_NAME : todos_db
  DB_VERSION : "10.4"
